# Action 的名字
name: Hexo Auto Deploy

on:
  # 触发条件1：main 分支收到 push 后执行任务。
  push:
    branches:
      - main
  # 触发条件2：手动按钮
  workflow_dispatch:

# 这里放环境变量
env:
  # Hexo 编译后使用此 git 用户部署到 github 仓库
  GIT_USER: DhuShen
  # Hexo 编译后使用此 git 邮箱部署到 github 仓库
  GIT_EMAIL: massd2002@163.com
  # Hexo 编译后要部署的 github 仓库
  GIT_DEPLOY_REPO: /dhushen.github.io
  # Hexo 编译后要部署到的分支
  GIT_DEPLOY_BRANCH: pages

  # 注意替换为你的 GitHub 源仓库地址
  GIT_SOURCE_REPO: git@github.com:dhushen/dhushen.github.io.git

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: windows-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        os: [windows-11]
        node_version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GIT_DEPLOY_REPO }}
          ref: ${{ env.GIT_DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Deploy hexo
        run: |
          hexo clean
          hexo g
          hexo d -g
